/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Kernel-version compatibility shims for seaweedvfs.
 *
 * The Linux in-kernel API is not stable: VFS hook signatures and helpers change
 * between releases. This header isolates those differences so the rest of the
 * module stays version-agnostic. Each shim is one self-contained unit, so the
 * complexity grows with the number of *changed APIs*, not the number of kernels.
 *
 * Supported range: 6.8 .. current mainline (7.0). The kernel build matrix
 * (.github/workflows/) compiles the module against each target kernel and is the
 * source of truth for what is actually supported — when a build there breaks,
 * add the shim here.
 *
 * Policy: LINUX_VERSION_CODE guards are fine for *mainline* API changes (version
 * numbers are reliable there). Enterprise distros (RHEL/SLES) backport features
 * into older version numbers, so for those use a Makefile compile-test (a
 * HAVE_* define from compat-config.h) instead of a version check — version
 * numbers lie. inode_state_read() below is the first such probe.
 */
#ifndef _SWVFS_COMPAT_H
#define _SWVFS_COMPAT_H

#include <linux/version.h>

/*
 * Feature-probe results (HAVE_* defines) generated by the top-level Makefile.
 * Guarded so a build that bypasses that Makefile still preprocesses (it just
 * falls back to the version-number paths below).
 */
#if defined(__has_include)
# if __has_include("compat-config.h")
#  include "compat-config.h"
# endif
#endif

/*
 * 6.13: inode_operations->mkdir returns `struct dentry *` instead of `int`
 * (NULL keeps the passed-in dentry, ERR_PTR(err) signals failure).
 * commit cd3e8c0c50a0e ("fs: change the signature of ->mkdir").
 */
#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 13, 0)
# define SWVFS_MKDIR_RET          struct dentry *
# define SWVFS_MKDIR_RESULT(err)  ((err) ? ERR_PTR(err) : NULL)
#else
# define SWVFS_MKDIR_RET          int
# define SWVFS_MKDIR_RESULT(err)  (err)
#endif

/*
 * Recent kernels wrap inode->i_state in a typed `struct inode_state_flags`, read
 * via inode_state_read*(). Detected by the feature probe HAVE_INODE_STATE_READ
 * (not a version number — the change is the sort distros backport). The I_NEW
 * check after iget_locked() is lockless, so use the _once (READ_ONCE) accessor.
 */
#ifdef HAVE_INODE_STATE_READ
# define SWVFS_I_STATE(inode)  inode_state_read_once(inode)
#else
# define SWVFS_I_STATE(inode)  ((inode)->i_state)
#endif

/*
 * ~6.10 moved struct file_lock's type/flags/pid/owner into an embedded
 * struct file_lock_core (fl->c.flc_*) and added lock_is_unlock()/lock_is_read().
 * Detected by the feature probe HAVE_FILE_LOCK_CORE. fl_start/fl_end stay on
 * file_lock in both layouts. The accessors are lvalues (used on both sides).
 */
#ifdef HAVE_FILE_LOCK_CORE
# define SWVFS_FL_IS_UNLOCK(fl)  lock_is_unlock(fl)
# define SWVFS_FL_IS_READ(fl)    lock_is_read(fl)
# define SWVFS_FL_TYPE(fl)       ((fl)->c.flc_type)
# define SWVFS_FL_FLAGS(fl)      ((fl)->c.flc_flags)
# define SWVFS_FL_PID(fl)        ((fl)->c.flc_pid)
# define SWVFS_FL_OWNER(fl)      ((fl)->c.flc_owner)
#else
# define SWVFS_FL_IS_UNLOCK(fl)  ((fl)->fl_type == F_UNLCK)
# define SWVFS_FL_IS_READ(fl)    ((fl)->fl_type == F_RDLCK)
# define SWVFS_FL_TYPE(fl)       ((fl)->fl_type)
# define SWVFS_FL_FLAGS(fl)      ((fl)->fl_flags)
# define SWVFS_FL_PID(fl)        ((fl)->fl_pid)
# define SWVFS_FL_OWNER(fl)      ((fl)->fl_owner)
#endif

/*
 * 6.3: VFS idmapping switched struct user_namespace* -> struct mnt_idmap* across
 * inode-op and xattr-handler signatures (and setattr_prepare/setattr_copy/
 * generic_fillattr). SWVFS_IDMAP is the first param of every such hook; passing
 * it through to the VFS helpers is type-correct on both layouts. Version-guarded
 * (not header-probed: the type exists via fs.h even where linux/mnt_idmap.h
 * isn't shipped separately); the only sub-6.3 in-scope kernel is mainline 6.1.
 */
#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 3, 0)
# define SWVFS_IDMAP struct mnt_idmap *
#else
# define SWVFS_IDMAP struct user_namespace *
#endif

/*
 * 6.6: inode mtime/atime setters, simple_inode_init_ts(), generic_fillattr()'s
 * request_mask arg, and memcpy_to_folio() landed together (inode_set_ctime*
 * predate 6.6 and are used directly). Mainline changes that no in-scope kernel
 * backports below 6.6 (the floor is mainline 6.1), so guard by version; on older
 * kernels the i_mtime/i_atime fields are still directly accessible.
 */
#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 6, 0)
# define SWVFS_INODE_SET_MTIME(inode, s, ns)  inode_set_mtime((inode), (s), (ns))
# define SWVFS_INODE_SET_ATIME(inode, s, ns)  inode_set_atime((inode), (s), (ns))
# define SWVFS_INODE_SET_MTIME_TS(inode, ts)  inode_set_mtime_to_ts((inode), (ts))
# define SWVFS_INODE_INIT_TS(inode)     simple_inode_init_ts(inode)
# define SWVFS_FILLATTR(idmap, mask, inode, stat) \
		generic_fillattr((idmap), (mask), (inode), (stat))
# define SWVFS_MEMCPY_TO_FOLIO(f, off, src, len) \
		memcpy_to_folio((f), (off), (src), (len))
#else
# define SWVFS_INODE_SET_MTIME(inode, s, ns) \
		((inode)->i_mtime = (struct timespec64){ .tv_sec = (s), .tv_nsec = (ns) })
# define SWVFS_INODE_SET_ATIME(inode, s, ns) \
		((inode)->i_atime = (struct timespec64){ .tv_sec = (s), .tv_nsec = (ns) })
# define SWVFS_INODE_SET_MTIME_TS(inode, ts)  ((inode)->i_mtime = (ts))
# define SWVFS_INODE_INIT_TS(inode) \
		((inode)->i_atime = (inode)->i_mtime = inode_set_ctime_current(inode))
# define SWVFS_FILLATTR(idmap, mask, inode, stat) \
		generic_fillattr((idmap), (inode), (stat))
/* 64-bit targets (amd64/arm64): folios live in the linear map, so
 * folio_address + offset is valid across the whole folio. */
# define SWVFS_MEMCPY_TO_FOLIO(f, off, src, len) \
		memcpy(folio_address(f) + (off), (src), (len))
#endif

/*
 * io_uring_cmd ring transport (optional fast path beside read()/write()). The
 * cmd API churns at both ends of 6.12: helpers like io_uring_cmd_to_pdu are not
 * all present until ~6.12, and the task-work/cmd API changes after it
 * (io_req_tw_func_t callbacks, 3-arg io_uring_cmd_done, 2-arg io_uring_sqe_cmd).
 * So gate the fast path to the 6.12.x window it is validated on; every other
 * kernel uses the char-device transport until it is re-ported. Needs CONFIG_IO_URING.
 */
#if defined(CONFIG_IO_URING) && \
    LINUX_VERSION_CODE >= KERNEL_VERSION(6, 12, 0) && \
    LINUX_VERSION_CODE <  KERNEL_VERSION(6, 13, 0)
# define SWVFS_HAVE_URING 1
#endif

#endif /* _SWVFS_COMPAT_H */
