/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Kernel-version compatibility shims for seaweedvfs.
 *
 * The Linux in-kernel API is not stable: VFS hook signatures and helpers change
 * between releases. This header isolates those differences so the rest of the
 * module stays version-agnostic. Each shim is one self-contained unit, so the
 * complexity grows with the number of *changed APIs*, not the number of kernels.
 *
 * Supported range: 6.1 LTS .. current mainline (7.0). The kernel build matrix
 * (.github/workflows/) compiles the module against each target kernel and is the
 * source of truth for what is actually supported — when a build there breaks,
 * add the shim here.
 *
 * Policy: LINUX_VERSION_CODE guards are fine for *mainline* API changes (version
 * numbers are reliable there). Enterprise distros (RHEL/SLES) backport features
 * into older version numbers, so for those use a Makefile compile-test (a
 * HAVE_* define from compat-config.h) instead of a version check — version
 * numbers lie. inode_state_read() below is the first such probe.
 */
#ifndef _SWVFS_COMPAT_H
#define _SWVFS_COMPAT_H

#include <linux/version.h>

/*
 * Feature-probe results (HAVE_* defines) generated by the top-level Makefile.
 * Guarded so a build that bypasses that Makefile still preprocesses (it just
 * falls back to the version-number paths below).
 */
#if defined(__has_include)
# if __has_include("compat-config.h")
#  include "compat-config.h"
# endif
#endif

/*
 * 6.13: inode_operations->mkdir returns `struct dentry *` instead of `int`
 * (NULL keeps the passed-in dentry, ERR_PTR(err) signals failure).
 * commit cd3e8c0c50a0e ("fs: change the signature of ->mkdir").
 */
#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 13, 0)
# define SWVFS_MKDIR_RET          struct dentry *
# define SWVFS_MKDIR_RESULT(err)  ((err) ? ERR_PTR(err) : NULL)
#else
# define SWVFS_MKDIR_RET          int
# define SWVFS_MKDIR_RESULT(err)  (err)
#endif

/*
 * Recent kernels wrap inode->i_state in a typed `struct inode_state_flags`, read
 * via inode_state_read*(). Detected by the feature probe HAVE_INODE_STATE_READ
 * (not a version number — the change is the sort distros backport). The I_NEW
 * check after iget_locked() is lockless, so use the _once (READ_ONCE) accessor.
 */
#ifdef HAVE_INODE_STATE_READ
# define SWVFS_I_STATE(inode)  inode_state_read_once(inode)
#else
# define SWVFS_I_STATE(inode)  ((inode)->i_state)
#endif

/*
 * io_uring_cmd ring transport (optional fast path beside read()/write()). The
 * io_uring task-work + cmd API changed substantially after 6.12 (io_req_tw_func_t
 * callbacks, 3-arg io_uring_cmd_done, 2-arg io_uring_sqe_cmd), so gate the fast
 * path to the kernels it is validated on; newer kernels fall back to the
 * char-device transport until it is re-ported. Requires CONFIG_IO_URING.
 */
#if defined(CONFIG_IO_URING) && LINUX_VERSION_CODE < KERNEL_VERSION(6, 13, 0)
# define SWVFS_HAVE_URING 1
#endif

#endif /* _SWVFS_COMPAT_H */
