# SPDX-License-Identifier: GPL-2.0
# Out-of-tree kbuild for the seaweedvfs kernel module.
#
# Build against the running kernel's headers by default:
#   make            # build seaweedvfs.ko
#   make clean
#   make KDIR=/lib/modules/<ver>/build   # build against a specific kernel

obj-m += seaweedvfs.o

KDIR ?= /lib/modules/$(shell uname -r)/build
PWD  := $(shell pwd)

all: compat-config.h
	$(MAKE) -C $(KDIR) M=$(PWD) modules

# Compat feature probes (ZFS-style): build a tiny module against the target
# kernel to detect an API, then emit a HAVE_* #define into compat-config.h,
# which compat.h includes. Robust across kernel versions and distro backports,
# where LINUX_VERSION_CODE lies. Each probe is one .c in compat-probes/.
compat-config.h: FORCE
	@echo "/* generated by 'make' feature probes — do not edit or commit */" > $@
	@if $(MAKE) -s -C $(KDIR) M=$(PWD)/compat-probes obj-m=inode_state_read.o \
		modules >/dev/null 2>&1; then \
		echo "#define HAVE_INODE_STATE_READ 1" >> $@; fi
	@$(MAKE) -s -C $(KDIR) M=$(PWD)/compat-probes clean >/dev/null 2>&1 || true

clean:
	$(MAKE) -C $(KDIR) M=$(PWD) clean
	@rm -f compat-config.h

FORCE:
.PHONY: all clean FORCE
