# SPDX-License-Identifier: GPL-2.0
# Out-of-tree kbuild for the seaweedvfs kernel module.
#
# Build against the running kernel's headers by default:
#   make            # build seaweedvfs.ko
#   make clean
#   make KDIR=/lib/modules/<ver>/build   # build against a specific kernel

obj-m += seaweedvfs.o

KDIR ?= /lib/modules/$(shell uname -r)/build
PWD  := $(shell pwd)

all: compat-config.h
	$(MAKE) -C $(KDIR) M=$(PWD) modules

# Compat feature probes (ZFS-style): build a tiny module against the target
# kernel to detect an API, then emit a HAVE_* #define into compat-config.h,
# which compat.h includes. Robust across kernel versions and distro backports,
# where LINUX_VERSION_CODE lies. Each probe is one .c in compat-probes/.
#
# probe(basename,DEFINE): build compat-probes/<basename>.c alone (via a one-line
# generated Kbuild) and emit #define DEFINE into compat-config.h if it compiles.
probe = printf 'obj-m := $(1).o\n' > compat-probes/Kbuild; \
	$(MAKE) -s -C $(KDIR) M=$(PWD)/compat-probes modules >/dev/null 2>&1 \
		&& echo "\#define $(2) 1" >> compat-config.h || true

compat-config.h: FORCE
	@echo "/* generated by 'make' feature probes — do not edit or commit */" > $@
	@$(call probe,inode_state_read,HAVE_INODE_STATE_READ)
	@$(call probe,file_lock_core,HAVE_FILE_LOCK_CORE)
	@rm -f compat-probes/Kbuild compat-probes/*.o compat-probes/*.ko \
		compat-probes/*.mod* compat-probes/.*.cmd \
		compat-probes/modules.order compat-probes/Module.symvers 2>/dev/null || true

clean:
	$(MAKE) -C $(KDIR) M=$(PWD) clean
	@rm -f compat-config.h

FORCE:
.PHONY: all clean FORCE
